version: '3.6'
services:
  gateone:
    image: kmlucy/docker-gateone
    ports:
    - "8080:8000"
    hostname: kubectl
    networks:
    - frontend
    volumes:
    - ssh_key:/root/.ssh/
  lab:
    image: arush/cka_lab
    ports:
    - "80:80"
    networks:
    - frontend
networks:
  frontend: {}
volumes:
  ssh_key: {}
